### ISSUE TITLE
How to be aware of the different OpenGL versions and methods?

### ISSUE THREAD

**Issue by norman784** [kotlin-graphics/gln#1]
I ask this b/c I don't see how to use methods supported only to certain version GL3 or GL4, I'm not a open GL guru so this is what helps me lwjgl to realice it.

**Comment by elect86** [comment]
Hello Norman :)

Well, this is something that still needs to be implemented...

The next step is, for example, to implement a setting for using [DSA](https://www.khronos.org/opengl/wiki/Direct_State_Access)

At the moment I only used (shaped and tuned) OpenGL 3.3+

Which version are you targetting?

**Comment by norman784** [comment]
Right now I'm not quite sure, I'm just started playing/learning OpenGL and its very useful to know in witch version is available each function, I've just tried [lwjgl](http://lwjgl.org) but b/c my goal is to use pure Kotlin (I really like the multi-platform support that will be available soon) so in a dream world I can have one code base and support multiple platforms.

**Comment by elect86** [comment]
Update: this must definitely be handled at the application level.

It's outside the scope of this library.

Feel free to reopen if you want to discuss this :)
