### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by Mitti30** [kotlin-graphics/gln#15]
Project is build with Gradle and at some Point it throws the the NoSuchMethodError, no matter which gln function i'm using.
`Exception in thread "main" java.lang.NoSuchMethodError: 'int gln.identifiers.GlProgram$Companion.create-qZPXwaU()'
	at helper.Renderer.initShaderProgram(Renderer.kt:32)
	at helper.Renderer.<init>(Renderer.kt:25)
	at MainKt.main(Main.kt:13)
	at MainKt.main(Main.kt)`

**Comment by elect86** [comment]
Is the project public?

**Comment by Mitti30** [comment]
Available under https://github.com/Mitti30/BreakoutOpenGL

**Comment by elect86** [comment]
I tracked down the problem: it's an incompatibility between the libs based on kotlin 1.3.72 and your kotlin runtime 1.4.0

I'll update them, but in the meanwhile you can downgrade temporarly

**Comment by Mitti30** [comment]
Thanks for the fast help

**Comment by elect86** [comment]
One last suggestion, if I may.

Don't use nullability on [gl objects](https://github.com/Mitti30/BreakoutOpenGL/blob/master/src/main/kotlin/helper/Renderer.kt#L14-L19), prefer this instead:

    private var vao = GlVertexArray(0) //.NULL has to be implemented yet
    private var vbo = GlBuffer(0)
    private var program = GlProgram.NULL

    private var fragmentShader = GlShader(0)
    private var vertexShader = GlShader(0)

At the moment only `GlProgram` has a confortable `.NULL`, I still have to add to the other objects
