### ISSUE TITLE
What is BlendEquationMode.LOGIC_OP?

### ISSUE THREAD

**Issue by Wasabi375** [kotlin-graphics/gln#5]
I looked for a documentation of `GL_LOGIC_OP` but I could not find any. Also Blending has a really detailed documentation [here](https://www.khronos.org/opengl/wiki/Blending) so I don't think `GL_LOGIC_OP` is a blending mode.

**Comment by elect86** [comment]
Nice catch dear

**Comment by elect86** [comment]
just an info, it was there because I wrongly copy/pasted from `BlendEquationModeExt`
